version: "3.8"

services:
  # Banco
  db:
    image: postgres:15
    container_name: sorteio-db
    environment:
      POSTGRES_DB: sorteio_db
      POSTGRES_USER: sorteio_user
      POSTGRES_PASSWORD: senha123
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend-net

  # Backend API 1
  api-sorteio-1:
    build: ./api-sorteio
    container_name: api-sorteio-1
    environment:
      DATABASE_URL: postgresql://sorteio_user:senha123@db:5432/sorteio_db
      SECRET_KEY: chave123
    depends_on:
      - db
    networks:
      - backend-net

  # Backend API 2
  api-sorteio-2:
    build: ./api-sorteio
    container_name: api-sorteio-2
    environment:
      DATABASE_URL: postgresql://sorteio_user:senha123@db:5432/sorteio_db
      SECRET_KEY: chave123
    depends_on:
      - db
    networks:
      - backend-net

  # Proxy Nginx com Load Balancer
  nginx:
    image: nginx:latest
    container_name: sorteio-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    depends_on:
      - api-sorteio-1
      - api-sorteio-2
    networks:
      - backend-net

networks:
  backend-net:

volumes:
  db_data:
